//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kisi
    {
        public int KisiID { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public string KisiEmail { get; set; }
        public string KisiFotograf { get; set; }
    }
}
